spring:
    application:
        name: discovery-server
#logging:
#    level:
#        root: "debug"
server:
    port: 8761
eureka:
    client:
        registerWithEureka: false
        fetchRegistry: false
